name: mapr
dependencies:
    args:
    threading:
    ansicolor:
    colorize: any
    dart_console:
    console:
    cli_repl:
    dcache:
    uuid: ^2.2.2
    tuple: ^1.0.3
    meta: ^1.2.4
    yaml: ^2.2.1
environment:
  sdk: '>=2.10.0 <3.0.0'

