name: mapr
dependencies:
    args: ^2.1.0
    ansicolor: ^2.0.1
    colorize: ^3.0.0
    dart_console: ^1.0.0
    console: ^4.1.0
    dcache: ^0.4.0
    uuid: ^3.0.4
    tuple: ^2.0.0
    meta: ^1.2.4
    yaml: ^3.1.0
environment:
  sdk: '>=2.12.0 <3.0.0'

